### ISSUE TITLE
Uncaught TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by davidhjp** [arrayoutofbounds/sysj#1]
Error dialog pops up when I try to run the program via hotkey 'Ctrl + Alt + A'.

StackTrace:
/C:/Users/machine01/.atom/packages/sysj/lib/sysj.coffee:388
Hide Stack Trace
TypeError: Cannot read property 'log' of undefined
    at Object.module.exports.Sysj.run (file:///C:/Users/machine01/.atom/packages/sysj/lib/sysj.coffee:451:39)
    at atom-workspace.subscriptions.add.atom.commands.add.sysj:run (file:///C:/Users/machine01/.atom/packages/sysj/lib/sysj.coffee:25:21)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (D:\Downloads\Atom\resources\app.asar\src\command-registry.js:260:29)
    at D:\Downloads\Atom\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (D:\Downloads\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (D:\Downloads\Atom\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (D:\Downloads\Atom\resources\app.asar\src\window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (D:\Downloads\Atom\resources\app.asar\src\window-event-handler.js:3:61)

**Comment by davidhjp** [comment]
I've used portable version of Atom FYI.

**Comment by arrayoutofbounds** [comment]
I fixed this....in the current patch. A popup shows up to tell the user to open a file before doing those operations
